# Generated by Django 5.0.6 on 2024-07-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='created_on',
        ),
    ]
